// {
//   "baseUrl": "http://localhost:3000",
//   "experimentalStudio": true // since that is true
// }

// check out the magic wand
// record
// right click on element to insert in assertions
// not perfect, but gets you 80% there
describe('Secret Menu with Cypress Studio', () => {
  beforeEach(() => {
    cy.visit('/secret-menu');
  });

  it('does stuff generated by Cypress Studio', () => {
    /* ==== Generated with Cypress Studio ==== */
    cy.get('#minimum-rating-visibility').click();
    cy.get('#restaurant-visibility-filter').select('KFC');
    cy.get('.whereToOrder > .cell').click();
    cy.get('.whereToOrder > .cell').click();
    cy.get('.whereToOrder > .cell').should('have.text', 'KFC');
    /* ==== End Cypress Studio ==== */
  });
});
